server:
  port: 8080
  servlet:
    context-path: /hotel

spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3301/Hotel_Booking_Management}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    password: ${DBMS_PASSWORD:root}
    username: ${DBMS_USERNAME:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
#  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  signerKey: "XPtCW+54S4SdZKvhWyFecy7onxF0kIpptVt2T/mLCBzVjBzS8qxGuwFuDR+fy0FQ"
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in seconds

picture:
    upload-dir: src/main/resources/static/images

sql:
  path: src/main/resources/static/SQL Script/

invoice:
  tax: 10